# Generated by Django 6.1.1 on 2026-09-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_position',
            field=models.CharField(default='center center', max_length=50),
        ),
    ]
